Card.destroy_all

Card.create name: 'The Magician', image: 'https://i.ibb.co/FBfBBqg/magician.jpg'
Card.create name: 'The High Priestess', image: 'https://i.ibb.co/RzkX1F0/high-priestess.jpg'
Card.create name: 'The Empress', image: 'https://i.ibb.co/NKxNdPC/empress.jpg'
Card.create name: 'The Emporer', image: 'https://i.ibb.co/sCX70Lr/emperor.jpg'
Card.create name: 'The Hierophant', image: 'https://i.ibb.co/0FDDwgk/hierophant.jpg'
Card.create name: 'The Lovers', image: 'https://i.ibb.co/426Trrw/lovers.jpg'
Card.create name: 'The Chariot', image: 'https://i.ibb.co/J7cYrnZ/chariot.jpg'
Card.create name: 'Fortitude', image: 'https://i.ibb.co/WgtqD3t/strength.jpg'
Card.create name: 'The Hermit', image: 'https://i.ibb.co/ZhKVvCG/hermit.jpg'
Card.create name: 'Wheel of Fortune', image: 'https://i.ibb.co/JtTZQRs/wheel-of-fortune.jpg'
Card.create name: 'Justice', image: 'https://i.ibb.co/dtCTMm3/justice.jpg'
Card.create name: 'The Hanged Man', image: 'https://i.ibb.co/02QJM2V/hanged-man.jpg'
Card.create name: 'Death', image: 'https://i.ibb.co/TBW9zCH/death.jpg'
Card.create name: 'Temperance', image: 'https://i.ibb.co/JCcLPSd/temperance.jpg'
Card.create name: 'Strength', image: 'https://i.ibb.co/WgtqD3t/strength.jpg'
Card.create name: 'The Devil', image: 'https://i.ibb.co/nj2dVrD/devil.jpg'
Card.create name: 'The Tower', image: 'https://i.ibb.co/846pqnx/tower.jpg'
Card.create name: 'The Star', image: 'https://i.ibb.co/pXy5Pfj/star.jpg'
Card.create name: 'The Moon', image: 'https://i.ibb.co/9bnvwnb/moon.jpg'
Card.create name: 'The Sun', image: 'https://i.ibb.co/BCbdYrT/sun.jpg'
Card.create name: 'The Last Judgement', image: 'https://i.ibb.co/3mM3ykQ/judgement.jpg'
Card.create name: 'The Fool', image: 'https://i.ibb.co/vZchhTV/fool.jpg'
Card.create name: 'The World', image: 'https://i.ibb.co/7rSfPSX/world.jpg'
Card.create name: 'Page of Wands', image: 'https://i.ibb.co/Wc4JbY5/page-of-wands.jpg'
Card.create name: 'Knight of Wands', image: 'https://i.ibb.co/LPkrNvc/knight-of-wands.jpg'
Card.create name: 'Queen of Wands', image: 'https://i.ibb.co/qyS3Y66/queen-of-wands.jpg'
Card.create name: 'King of Wands', image: 'https://i.ibb.co/SnYJVgG/king-of-wands.jpg'
Card.create name: 'Ace of Wands', image: 'https://i.ibb.co/TRyZYhq/ace-of-wands.jpg'
Card.create name: 'Two of Wands', image: 'https://i.ibb.co/hW3HZLP/two-of-wands.jpg'
Card.create name: 'Three of Wands', image: 'https://i.ibb.co/bFLdDcr/three-of-wands.jpg'
Card.create name: 'Four of Wands', image: 'https://i.ibb.co/Wsc38MK/four-of-wands.jpg'
Card.create name: 'Five of Wands', image: 'https://i.ibb.co/X3Y98Zt/five-of-wands.jpg'
Card.create name: 'Six of Wands', image: 'https://i.ibb.co/NxP2LP4/six-of-wands.jpg'
Card.create name: 'Seven of Wands', image: 'https://i.ibb.co/wr8p3cy/seven-of-wands.jpg'
Card.create name: 'Eight of Wands', image: 'https://i.ibb.co/F4NtgCL/eight-of-wands.jpg'
Card.create name: 'Nine of Wands', image: 'https://i.ibb.co/RTjT812/nine-of-wands.jpg'
Card.create name: 'Ten of Wands', image: 'https://i.ibb.co/6tXcy6D/ten-of-wands.jpg'
Card.create name: 'Page of Cups', image: 'https://i.ibb.co/wzhMMCH/page-of-cups.jpg'
Card.create name: 'Knight of Cups', image: 'https://i.ibb.co/NW7YXvK/knight-of-cups.jpg'
Card.create name: 'Queen of Cups', image: 'https://i.ibb.co/brG0cxD/queen-of-cups.jpg'
Card.create name: 'King of Cups', image: 'https://i.ibb.co/9v7WgXZ/king-of-cups.jpg'
Card.create name: 'Ace of Cups', image: 'https://i.ibb.co/YpQCxCs/ace-of-cups.jpg'
Card.create name: 'Two of Cups', image: 'https://i.ibb.co/KXMsQG8/two-of-cups.jpg'
Card.create name: 'Three of Cups', image: 'https://i.ibb.co/HKkbkT1/three-of-cups.jpg'
Card.create name: 'Four of Cups', image: 'https://i.ibb.co/DKynLQk/four-of-cups.jpg'
Card.create name: 'Five of Cups', image: 'https://i.ibb.co/JHQbmcq/five-of-cups.jpg'
Card.create name: 'Six of Cups', image: 'https://i.ibb.co/Jv9dW05/six-of-cups.jpg'
Card.create name: 'Seven of Cups', image: 'https://i.ibb.co/DrSN9d7/seven-of-cups.jpg'
Card.create name: 'Eight of Cups', image: 'https://i.ibb.co/VHPc7TC/eight-of-cups.jpg'
Card.create name: 'Nine of Cups', image: 'https://i.ibb.co/CnYMQcK/nine-of-cups.jpg'
Card.create name: 'Ten of Cups', image: 'https://i.ibb.co/FwHLrVx/ten-of-cups.jpg'
Card.create name: 'Page of Pentacles', image: 'https://i.ibb.co/9tG2GWS/page-of-pentacles.jpg'
Card.create name: 'Knight of Pentacles', image: 'https://i.ibb.co/2cjkpRm/knight-of-pentacles.jpg'
Card.create name: 'Queen of Pentacles', image: 'https://i.ibb.co/T0mMhkn/queen-of-pentacles.jpg'
Card.create name: 'King of Pentacles', image: 'https://i.ibb.co/xGydhYk/king-of-pentacles.jpg'
Card.create name: 'Ace of Pentacles', image: 'https://i.ibb.co/dJmXTTc/ace-of-pentacles.jpg'
Card.create name: 'Two of Pentacles', image: 'https://i.ibb.co/k6R19cn/two-of-pentacles.jpg'
Card.create name: 'Three of Pentacles', image: 'https://i.ibb.co/B2csL9r/three-of-pentacles.jpg'
Card.create name: 'Four of Pentacles', image: 'https://i.ibb.co/d49Vc9S/four-of-pentacles.jpg'
Card.create name: 'Five of Pentacles', image: 'https://i.ibb.co/CmRDv02/five-of-pentacles.jpg'
Card.create name: 'Six of Pentacles', image: 'https://i.ibb.co/dMxPRZG/six-of-pentacles.jpg'
Card.create name: 'Seven of Pentacles', image: 'https://i.ibb.co/QDwnvLZ/seven-of-pentacles.jpg'
Card.create name: 'Eight of Pentacles', image: 'https://i.ibb.co/myg0cP5/eight-of-pentacles.jpg'
Card.create name: 'Nine of Pentacles', image: 'https://i.ibb.co/Wn5fmQR/nine-of-pentacles.jpg'
Card.create name: 'Ten of Pentacles', image: 'https://i.ibb.co/vDF62tY/ten-of-pentacles.jpg'
Card.create name: 'Page of Swords', image: 'https://i.ibb.co/dPGn6R1/page-of-swords.jpg'
Card.create name: 'Knight of Swords', image: 'https://i.ibb.co/xqMjHVB/knight-of-swords.jpg'
Card.create name: 'Queen of Swords', image: 'https://i.ibb.co/bd1K1kX/queen-of-swords.jpg'
Card.create name: 'King of Swords', image: 'https://i.ibb.co/7JZXbt4/king-of-swords.jpg'
Card.create name: 'Ace of Swords', image: 'https://i.ibb.co/v3c4Ny9/ace-of-swords.jpg'
Card.create name: 'Two of Swords', image: 'https://i.ibb.co/F3zw2JZ/two-of-swords.jpg'
Card.create name: 'Three of Swords', image: 'https://i.ibb.co/f997hd4/three-of-swords.jpg'
Card.create name: 'Four of Swords', image: 'https://i.ibb.co/QKR7n4x/four-of-swords.jpg'
Card.create name: 'Five of Swords', image: 'https://i.ibb.co/K56sLbH/five-of-swords.jpg'
Card.create name: 'Six of Swords', image: 'https://i.ibb.co/sm1fhyh/six-of-swords.jpg'
Card.create name: 'Seven of Swords', image: 'https://i.ibb.co/M9ZS1zz/seven-of-swords.jpg'
Card.create name: 'Eight of Swords', image: 'https://i.ibb.co/WP1S1JK/eight-of-swords.jpg'
Card.create name: 'Nine of Swords', image: 'https://i.ibb.co/LQjTYDd/nine-of-swords.jpg'
Card.create name: 'Ten of Swords', image: 'https://i.ibb.co/P5XHbxQ/ten-of-swords.jpg'