Card.destroy_all

Card.create name: 'The Magician', image: 'https://i.ibb.co/FBfBBqg/magician.jpg', short_name: 'ar01'
Card.create name: 'The High Priestess', image: 'https://i.ibb.co/RzkX1F0/high-priestess.jpg', short_name: 'ar02'
Card.create name: 'The Empress', image: 'https://i.ibb.co/NKxNdPC/empress.jpg', short_name: 'ar03'
Card.create name: 'The Emporer', image: 'https://i.ibb.co/sCX70Lr/emperor.jpg', short_name: 'ar04'
Card.create name: 'The Hierophant', image: 'https://i.ibb.co/0FDDwgk/hierophant.jpg', short_name: 'ar05'
Card.create name: 'The Lovers', image: 'https://i.ibb.co/426Trrw/lovers.jpg', short_name: 'ar06'
Card.create name: 'The Chariot', image: 'https://i.ibb.co/J7cYrnZ/chariot.jpg', short_name: 'ar07'
Card.create name: 'Fortitude', image: 'https://i.ibb.co/WgtqD3t/strength.jpg', short_name: 'ar08'
Card.create name: 'The Hermit', image: 'https://i.ibb.co/ZhKVvCG/hermit.jpg', short_name: 'ar09'
Card.create name: 'Wheel of Fortune', image: 'https://i.ibb.co/JtTZQRs/wheel-of-fortune.jpg', short_name: 'ar10'
Card.create name: 'Justice', image: 'https://i.ibb.co/dtCTMm3/justice.jpg', short_name: 'ar11'
Card.create name: 'The Hanged Man', image: 'https://i.ibb.co/02QJM2V/hanged-man.jpg', short_name: 'ar12'
Card.create name: 'Death', image: 'https://i.ibb.co/TBW9zCH/death.jpg', short_name: 'ar13'
Card.create name: 'Temperance', image: 'https://i.ibb.co/JCcLPSd/temperance.jpg', short_name: 'ar14'
# Card.create name: 'Strength', image: 'https://i.ibb.co/WgtqD3t/strength.jpg', short_name: ''
Card.create name: 'The Devil', image: 'https://i.ibb.co/nj2dVrD/devil.jpg', short_name: 'ar15'
Card.create name: 'The Tower', image: 'https://i.ibb.co/846pqnx/tower.jpg', short_name: 'ar16'
Card.create name: 'The Star', image: 'https://i.ibb.co/pXy5Pfj/star.jpg', short_name: 'ar17'
Card.create name: 'The Moon', image: 'https://i.ibb.co/9bnvwnb/moon.jpg', short_name: 'ar18'
Card.create name: 'The Sun', image: 'https://i.ibb.co/BCbdYrT/sun.jpg', short_name: 'ar19'
Card.create name: 'The Last Judgement', image: 'https://i.ibb.co/3mM3ykQ/judgement.jpg', short_name: 'ar20'
Card.create name: 'The Fool', image: 'https://i.ibb.co/vZchhTV/fool.jpg', short_name: 'ar00'
Card.create name: 'The World', image: 'https://i.ibb.co/7rSfPSX/world.jpg', short_name: 'ar21'
Card.create name: 'Page of Wands', image: 'https://i.ibb.co/Wc4JbY5/page-of-wands.jpg', short_name: 'wapa'
Card.create name: 'Knight of Wands', image: 'https://i.ibb.co/LPkrNvc/knight-of-wands.jpg', short_name: 'wakn'
Card.create name: 'Queen of Wands', image: 'https://i.ibb.co/qyS3Y66/queen-of-wands.jpg', short_name: 'waqu'
Card.create name: 'King of Wands', image: 'https://i.ibb.co/SnYJVgG/king-of-wands.jpg', short_name: 'waki'
Card.create name: 'Ace of Wands', image: 'https://i.ibb.co/TRyZYhq/ace-of-wands.jpg', short_name: 'waac'
Card.create name: 'Two of Wands', image: 'https://i.ibb.co/hW3HZLP/two-of-wands.jpg', short_name: 'wa02'
Card.create name: 'Three of Wands', image: 'https://i.ibb.co/bFLdDcr/three-of-wands.jpg', short_name: 'wa03'
Card.create name: 'Four of Wands', image: 'https://i.ibb.co/Wsc38MK/four-of-wands.jpg', short_name: 'wa04'
Card.create name: 'Five of Wands', image: 'https://i.ibb.co/X3Y98Zt/five-of-wands.jpg', short_name: 'wa05'
Card.create name: 'Six of Wands', image: 'https://i.ibb.co/NxP2LP4/six-of-wands.jpg', short_name: 'wa06'
Card.create name: 'Seven of Wands', image: 'https://i.ibb.co/wr8p3cy/seven-of-wands.jpg', short_name: 'wa07'
Card.create name: 'Eight of Wands', image: 'https://i.ibb.co/F4NtgCL/eight-of-wands.jpg', short_name: 'wa08'
Card.create name: 'Nine of Wands', image: 'https://i.ibb.co/RTjT812/nine-of-wands.jpg', short_name: 'wa09'
Card.create name: 'Ten of Wands', image: 'https://i.ibb.co/6tXcy6D/ten-of-wands.jpg', short_name: 'wa10'
Card.create name: 'Page of Cups', image: 'https://i.ibb.co/wzhMMCH/page-of-cups.jpg', short_name: 'cupa'
Card.create name: 'Knight of Cups', image: 'https://i.ibb.co/NW7YXvK/knight-of-cups.jpg', short_name: 'cukn'
Card.create name: 'Queen of Cups', image: 'https://i.ibb.co/brG0cxD/queen-of-cups.jpg', short_name: 'cuqu'
Card.create name: 'King of Cups', image: 'https://i.ibb.co/9v7WgXZ/king-of-cups.jpg', short_name: 'cuki'
Card.create name: 'Ace of Cups', image: 'https://i.ibb.co/YpQCxCs/ace-of-cups.jpg', short_name: 'cuac'
Card.create name: 'Two of Cups', image: 'https://i.ibb.co/KXMsQG8/two-of-cups.jpg', short_name: 'cu02'
Card.create name: 'Three of Cups', image: 'https://i.ibb.co/HKkbkT1/three-of-cups.jpg', short_name: 'cu03'
Card.create name: 'Four of Cups', image: 'https://i.ibb.co/DKynLQk/four-of-cups.jpg', short_name: 'cu04'
Card.create name: 'Five of Cups', image: 'https://i.ibb.co/JHQbmcq/five-of-cups.jpg', short_name: 'cu05'
Card.create name: 'Six of Cups', image: 'https://i.ibb.co/Jv9dW05/six-of-cups.jpg', short_name: 'cu06'
Card.create name: 'Seven of Cups', image: 'https://i.ibb.co/DrSN9d7/seven-of-cups.jpg', short_name: 'cu07'
Card.create name: 'Eight of Cups', image: 'https://i.ibb.co/VHPc7TC/eight-of-cups.jpg', short_name: 'cu08'
Card.create name: 'Nine of Cups', image: 'https://i.ibb.co/CnYMQcK/nine-of-cups.jpg', short_name: 'cu09'
Card.create name: 'Ten of Cups', image: 'https://i.ibb.co/FwHLrVx/ten-of-cups.jpg', short_name: 'cu10'
Card.create name: 'Page of Pentacles', image: 'https://i.ibb.co/9tG2GWS/page-of-pentacles.jpg', short_name: 'pepa'
Card.create name: 'Knight of Pentacles', image: 'https://i.ibb.co/2cjkpRm/knight-of-pentacles.jpg', short_name: 'pekn'
Card.create name: 'Queen of Pentacles', image: 'https://i.ibb.co/T0mMhkn/queen-of-pentacles.jpg', short_name: 'pequ'
Card.create name: 'King of Pentacles', image: 'https://i.ibb.co/xGydhYk/king-of-pentacles.jpg', short_name: 'peki'
Card.create name: 'Ace of Pentacles', image: 'https://i.ibb.co/dJmXTTc/ace-of-pentacles.jpg', short_name: 'peac'
Card.create name: 'Two of Pentacles', image: 'https://i.ibb.co/k6R19cn/two-of-pentacles.jpg', short_name: 'pe02'
Card.create name: 'Three of Pentacles', image: 'https://i.ibb.co/B2csL9r/three-of-pentacles.jpg', short_name: 'pe03'
Card.create name: 'Four of Pentacles', image: 'https://i.ibb.co/d49Vc9S/four-of-pentacles.jpg', short_name: 'pe04'
Card.create name: 'Five of Pentacles', image: 'https://i.ibb.co/CmRDv02/five-of-pentacles.jpg', short_name: 'pe05'
Card.create name: 'Six of Pentacles', image: 'https://i.ibb.co/dMxPRZG/six-of-pentacles.jpg', short_name: 'pe06'
Card.create name: 'Seven of Pentacles', image: 'https://i.ibb.co/QDwnvLZ/seven-of-pentacles.jpg', short_name: 'pe07'
Card.create name: 'Eight of Pentacles', image: 'https://i.ibb.co/myg0cP5/eight-of-pentacles.jpg', short_name: 'pe08'
Card.create name: 'Nine of Pentacles', image: 'https://i.ibb.co/Wn5fmQR/nine-of-pentacles.jpg', short_name: 'pe09'
Card.create name: 'Ten of Pentacles', image: 'https://i.ibb.co/vDF62tY/ten-of-pentacles.jpg', short_name: 'pe10'
Card.create name: 'Page of Swords', image: 'https://i.ibb.co/dPGn6R1/page-of-swords.jpg', short_name: 'swpa'
Card.create name: 'Knight of Swords', image: 'https://i.ibb.co/xqMjHVB/knight-of-swords.jpg', short_name: 'swkn'
Card.create name: 'Queen of Swords', image: 'https://i.ibb.co/bd1K1kX/queen-of-swords.jpg', short_name: 'swqu'
Card.create name: 'King of Swords', image: 'https://i.ibb.co/7JZXbt4/king-of-swords.jpg', short_name: 'swki'
Card.create name: 'Ace of Swords', image: 'https://i.ibb.co/v3c4Ny9/ace-of-swords.jpg', short_name: 'swac'
Card.create name: 'Two of Swords', image: 'https://i.ibb.co/F3zw2JZ/two-of-swords.jpg', short_name: 'sw02'
Card.create name: 'Three of Swords', image: 'https://i.ibb.co/f997hd4/three-of-swords.jpg', short_name: 'sw03'
Card.create name: 'Four of Swords', image: 'https://i.ibb.co/QKR7n4x/four-of-swords.jpg', short_name: 'sw04'
Card.create name: 'Five of Swords', image: 'https://i.ibb.co/K56sLbH/five-of-swords.jpg', short_name: 'sw05'
Card.create name: 'Six of Swords', image: 'https://i.ibb.co/sm1fhyh/six-of-swords.jpg', short_name: 'sw06'
Card.create name: 'Seven of Swords', image: 'https://i.ibb.co/M9ZS1zz/seven-of-swords.jpg', short_name: 'sw07'
Card.create name: 'Eight of Swords', image: 'https://i.ibb.co/WP1S1JK/eight-of-swords.jpg', short_name: 'sw08'
Card.create name: 'Nine of Swords', image: 'https://i.ibb.co/LQjTYDd/nine-of-swords.jpg', short_name: 'sw09'
Card.create name: 'Ten of Swords', image: 'https://i.ibb.co/P5XHbxQ/ten-of-swords.jpg', short_name: 'sw10'